version: '3.6'
services:
  iris:
    build:
      context: .
      args:
        openai_api_key: <open-api-key>
      dockerfile: Dockerfile
    restart: always
    #   command: --check-caps false
    ports:
      - 51773:1972
      - 52773:52773
      - 53773:52773
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
